version: '3.8'

services:
  # 🧠 Contenedor de la API e Ingesta
  saktishield-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    # 🟢 INYECTAMOS LAS VARIABLES DE ENTORNO (Token de Telegram y Chat ID)
    env_file:
      - .env
    # 🔗 Esto le permite al contenedor hablar con el Ollama de tu Mac
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # 💾 Esto evita que la base de datos se borre al reiniciar, arreglando la correlación
    volumes:
      - ./security_vault.db:/app/security_vault.db  # Compartimos la DB local para que no se borren los datos al apagar el contenedor
      - ./blacklist.txt:/app/blacklist.txt
    depends_on:
      - saktishield-db  # 🐘 Forzamos a que la base de datos levante antes que el backend

  # 📊 Contenedor del Dashboard OLED
  saktishield-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    # 🟢 NUEVO: Inyectamos variables para que Streamlit sepa dónde está PostgreSQL en Docker
    environment:
      - DB_HOST=saktishield-db
      - DB_NAME=saktishield_production
      - DB_USER=sakti_admin
      - DB_PASSWORD=SaktiSecurePassword2026!
      - DB_PORT=5432
    env_file:
      - .env
    depends_on:
      - saktishield-db
      - saktishield-backend
    volumes:
      - ./app_saas.py:/app/app_saas.py
      - ./security_vault.db:/app/security_vault.db
      - ./logo_sakti.png:/app/logo_sakti.png

  # 🐘 MOTOR DE BASE DE DATOS CORPORATIVO (PostgreSQL)
  saktishield-db:
    image: postgres:15-alpine
    container_name: threat_orchestrator-saktishield-db-1
    restart: always
    environment:
      POSTGRES_USER: sakti_admin
      POSTGRES_PASSWORD: SaktiSecurePassword2026!  # Clave corporativa de administración
      POSTGRES_DB: saktishield_production
    ports:
      - "5432:5432"
    volumes:
      - postgres_corporate_data:/var/lib/postgresql/data

# 💾 VOLÚMENES GLOBALES PERSISTENTES
volumes:
  postgres_corporate_data:  # Garantiza que la data corporativa de Postgres no se borre al apagar Docker