# 1. Imagen base de Python ligera
FROM python:3.11-slim

# 2. Directorio de trabajo
WORKDIR /app

# 3. Copiamos e instalamos dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copiamos el archivo de la interfaz de usuario y la base de datos para lectura
COPY app_saas.py .
COPY logo_sakti.png .
COPY security_vault.db .

# 5. Exponemos el puerto 8501 que usa Streamlit por defecto
EXPOSE 8501

# 6. Comando para arrancar el Dashboard en modo corporativo
CMD ["streamlit", "run", "app_saas.py", "--server.port=8501", "--server.address=0.0.0.0"]